version: '3.8'

services:
  web: 
    build:  .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-w4p^5*3zeebdz6r=021sein4mcm551o+n9%vfhf=i9dd^efzgv
      - DEBUG=1
      - DATABASE_URL=postgres://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/dbname # Lembre-se de configurar isso para 'postgres://POSTGRES_USER:POSTGRES_PASSWORD@db:5432/dbname' ou similar depois
    depends_on:
      - db
    

  db: 
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 

    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=POSTGRES_USER 
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    restart: unless-stopped


volumes: 
  postgres_data: 
    