services:
  web:
    build: .
    command: sh -c "./wait-for-db.sh db 5432 python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgres://jadson:285903@db:5432/dbname
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"  # <--- Adicionado aqui


  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=jadson
      - POSTGRES_PASSWORD=285903
      - POSTGRES_DB=dbname
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jadson -d dbname"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: